// Shared sample hotel-name data for Tripora's enquiry preview.
// This is NOT live supplier inventory. TBO API data must replace/enrich it after access is enabled.
window.TRIPORA_HOTELS = [
  {n:"Taj Palace, New Delhi",c:"New Delhi",o:"India"},
  {n:"The Leela Palace New Delhi",c:"New Delhi",o:"India"},
  {n:"ITC Maurya, a Luxury Collection Hotel",c:"New Delhi",o:"India"},
  {n:"The Imperial New Delhi",c:"New Delhi",o:"India"},
  {n:"The Lalit New Delhi",c:"New Delhi",o:"India"},
  {n:"JW Marriott Hotel New Delhi Aerocity",c:"New Delhi",o:"India"},
  {n:"Radisson Blu Plaza Delhi Airport",c:"New Delhi",o:"India"},
  {n:"The Oberoi Gurgaon",c:"Gurugram",o:"India"},
  {n:"Trident Gurgaon",c:"Gurugram",o:"India"},
  {n:"Taj City Centre Gurugram",c:"Gurugram",o:"India"},
  {n:"The Leela Ambience Gurugram Hotel & Residences",c:"Gurugram",o:"India"},
  {n:"Taj Mahal Palace, Mumbai",c:"Mumbai",o:"India"},
  {n:"The Oberoi Mumbai",c:"Mumbai",o:"India"},
  {n:"Trident Nariman Point",c:"Mumbai",o:"India"},
  {n:"ITC Maratha, a Luxury Collection Hotel",c:"Mumbai",o:"India"},
  {n:"The St. Regis Mumbai",c:"Mumbai",o:"India"},
  {n:"Taj Santacruz",c:"Mumbai",o:"India"},
  {n:"Taj Exotica Resort & Spa, Goa",c:"Goa",o:"India"},
  {n:"W Goa",c:"Goa",o:"India"},
  {n:"The Leela Goa",c:"Goa",o:"India"},
  {n:"ITC Grand Goa Resort & Spa",c:"Goa",o:"India"},
  {n:"Grand Hyatt Goa",c:"Goa",o:"India"},
  {n:"Taj Fort Aguada Resort & Spa",c:"Goa",o:"India"},
  {n:"Taj West End",c:"Bengaluru",o:"India"},
  {n:"The Leela Palace Bengaluru",c:"Bengaluru",o:"India"},
  {n:"ITC Gardenia, a Luxury Collection Hotel",c:"Bengaluru",o:"India"},
  {n:"The Oberoi Bengaluru",c:"Bengaluru",o:"India"},
  {n:"Taj Krishna",c:"Hyderabad",o:"India"},
  {n:"ITC Kohenur, a Luxury Collection Hotel",c:"Hyderabad",o:"India"},
  {n:"Taj Deccan",c:"Hyderabad",o:"India"},
  {n:"The Leela Palace Chennai",c:"Chennai",o:"India"},
  {n:"ITC Grand Chola",c:"Chennai",o:"India"},
  {n:"Taj Coromandel",c:"Chennai",o:"India"},
  {n:"Taj Bengal",c:"Kolkata",o:"India"},
  {n:"ITC Royal Bengal",c:"Kolkata",o:"India"},
  {n:"The Oberoi Grand Kolkata",c:"Kolkata",o:"India"},
  {n:"Rambagh Palace",c:"Jaipur",o:"India"},
  {n:"The Oberoi Rajvilas Jaipur",c:"Jaipur",o:"India"},
  {n:"ITC Rajputana, a Luxury Collection Hotel",c:"Jaipur",o:"India"},
  {n:"Taj Jai Mahal Palace",c:"Jaipur",o:"India"},
  {n:"Taj Lake Palace",c:"Udaipur",o:"India"},
  {n:"The Oberoi Udaivilas",c:"Udaipur",o:"India"},
  {n:"Trident Udaipur",c:"Udaipur",o:"India"},
  {n:"The Oberoi Amarvilas",c:"Agra",o:"India"},
  {n:"ITC Mughal, a Luxury Collection Resort & Spa",c:"Agra",o:"India"},
  {n:"Taj Hotel & Convention Centre Agra",c:"Agra",o:"India"},
  {n:"Taj Rishikesh Resort & Spa",c:"Rishikesh",o:"India"},
  {n:"Aloha On The Ganges",c:"Rishikesh",o:"India"},
  {n:"Taj Madikeri Resort & Spa",c:"Coorg",o:"India"},
  {n:"The Leela Palace Udaipur",c:"Udaipur",o:"India"},
  {n:"Taj Corbett Resort & Spa",c:"Corbett",o:"India"},
  {n:"The Oberoi Cecil",c:"Shimla",o:"India"},
  {n:"Wildflower Hall, An Oberoi Resort",c:"Shimla",o:"India"},
  {n:"Hyatt Regency Delhi",c:"New Delhi",o:"India"},
  {n:"Hyatt Regency Mumbai",c:"Mumbai",o:"India"},
  {n:"Hyatt Regency Goa Resort and Spa",c:"Goa",o:"India"},
  {n:"Taj Dubai",c:"Dubai",o:"United Arab Emirates"},
  {n:"Burj Al Arab Jumeirah",c:"Dubai",o:"United Arab Emirates"},
  {n:"Atlantis, The Palm",c:"Dubai",o:"United Arab Emirates"},
  {n:"JW Marriott Marquis Hotel Dubai",c:"Dubai",o:"United Arab Emirates"},
  {n:"Jumeirah Beach Hotel",c:"Dubai",o:"United Arab Emirates"},
  {n:"The Ritz-Carlton Dubai",c:"Dubai",o:"United Arab Emirates"},
  {n:"Palace Downtown",c:"Dubai",o:"United Arab Emirates"},
  {n:"Raffles Dubai",c:"Dubai",o:"United Arab Emirates"},
  {n:"Emirates Palace Mandarin Oriental",c:"Abu Dhabi",o:"United Arab Emirates"},
  {n:"The Ritz-Carlton Abu Dhabi, Grand Canal",c:"Abu Dhabi",o:"United Arab Emirates"},
  {n:"The Savoy",c:"London",o:"United Kingdom"},
  {n:"The Ritz London",c:"London",o:"United Kingdom"},
  {n:"The Langham, London",c:"London",o:"United Kingdom"},
  {n:"The Dorchester",c:"London",o:"United Kingdom"},
  {n:"Park Hyatt Paris-Vendôme",c:"Paris",o:"France"},
  {n:"The Ritz Paris",c:"Paris",o:"France"},
  {n:"Shangri-La Paris",c:"Paris",o:"France"},
  {n:"The Plaza",c:"New York",o:"United States"},
  {n:"The St. Regis New York",c:"New York",o:"United States"},
  {n:"Park Hyatt New York",c:"New York",o:"United States"},
  {n:"Marina Bay Sands",c:"Singapore",o:"Singapore"},
  {n:"Raffles Singapore",c:"Singapore",o:"Singapore"},
  {n:"The Fullerton Hotel Singapore",c:"Singapore",o:"Singapore"},
  {n:"The Peninsula Hong Kong",c:"Hong Kong",o:"Hong Kong"},
  {n:"The Tokyo Station Hotel",c:"Tokyo",o:"Japan"},
  {n:"Park Hyatt Tokyo",c:"Tokyo",o:"Japan"},
  {n:"The Peninsula Tokyo",c:"Tokyo",o:"Japan"},
  {n:"The Grand Hyatt Bangkok",c:"Bangkok",o:"Thailand"},
  {n:"The Peninsula Bangkok",c:"Bangkok",o:"Thailand"},
  {n:"The Westin Resort Nusa Dua",c:"Bali",o:"Indonesia"},
  {n:"Four Seasons Resort Bali at Sayan",c:"Bali",o:"Indonesia"},
  {n:"The St. Regis Maldives Vommuli Resort",c:"Maldives",o:"Maldives"},
  {n:"Anantara Iko Mauritius Resort & Villas",c:"Mauritius",o:"Mauritius"},
  {n:"Burj Al Arab",c:"Dubai",o:"United Arab Emirates"}
];
